version: '3.8'

services:

  #Defines the nginx service
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
      - "8081:8081"

  #Defines the tests service
  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - nginx
    network_mode: "service:nginx"
