name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
          
      - name: Run Tests
        run: |
          docker-compose exec tester python /test_servers.py
          
      - name: Save Result
        run: |
          if [ $? -eq 0 ]; then
            echo "succeeded" > result.txt
          else
            echo "fail" > result.txt
          fi

      - name: Upload result to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.txt
